uvmf:
  environments:
    control:
      agents:
      - initiator_responder: RESPONDER
        name: control_in_agent
        type: control_in
      - initiator_responder: RESPONDER
        name: control_out_agent
        type: control_out
      analysis_components:
      - name: control_predictor
        parameters: []
        type: control_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: control_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: control_out_transaction
      subenvs: []
      tlm_connections:
      - driver: control_in_agent.monitored_ap
        receiver: control_predictor.control_in_agent_ae
        validate: 'True'
      - driver: control_predictor.scoreboard_ap
        receiver: control_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: control_out_agent.monitored_ap
        receiver: control_scoreboard.actual_analysis_export
        validate: 'True'
